## Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: OTSTask@3
  inputs:
    OTSService: 'DevOps TestHub'
    teamspace: 'Initial Team Space'
    project: 'Emeral_Demo'
    branch: 'main'
    repo: 'https://github.com/oresteegidio/EmeraldDemo'
    filePath: 'Emerald-UI-Tests/Bath_Search.testsuite'
    exportReport: '$(Agent.TempDirectory)/exportReport.xml'
- task: PublishTestResults@2
  condition: always()
  inputs:
    testResultsFormat: 'JUnit'
    testResultsFiles: '$(Agent.TempDirectory)/exportReport.xml'
    searchFolder: '$(Agent.TempDirectory)'
    mergeTestResults: true
    failTaskOnFailedTests: true
    testRunTitle: 'SBD Test'